server:
  port: 8888
spring:
  profiles:
    active: native
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: C:\Users\playdata2\Desktop\develop\git-local-repo
#        git:
#          uri: C:\Users\playdata2\Desktop\develop\git-local-repo
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans

