server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: C:\Users\playdata2\Desktop\develop\git-local-repo
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans

